export async function seed(knex) {
  await knex('outfits').insert([
    {
      id: 1,
      user_id: 'auth0|65010b645218b17b091d01fe',
      img: 'https://exxpozed-image.de/exxpozed-res.cloudinary.com/image/upload/q_auto:eco,w_1500,h_1500,c_pad,b_white,d_ph.gif,e_sharpen/v20230814123732/catalog/the-north-face-w-cragmont-fleece-jacket-21b-tnf-nf0a5a9l-gardenia-white-1.jpg',
      date_posted: new Date(Date.now()),
      description:
        '1fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck ',
      top_id: 1,
      bottom_id: 3,
      outer_id: null,
      accessories_id: null,
      footwear_id: null,
    },
    {
      id: 2,
      user_id: 'auth0|65010b645218b17b091d01fe',
      img: 'https://exxpozed-image.de/exxpozed-res.cloudinary.com/image/upload/q_auto:eco,w_1500,h_1500,c_pad,b_white,d_ph.gif,e_sharpen/v20230814123732/catalog/the-north-face-w-cragmont-fleece-jacket-21b-tnf-nf0a5a9l-gardenia-white-1.jpg',
      date_posted: new Date(Date.now()),
      description:
        '2fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck fuck ',
      top_id: 1,
      bottom_id: 3,
      outer_id: null,
      accessories_id: null,
      footwear_id: null,
    },
    {
      id: 3,
      user_id: 'auth0|65010b645218b17b091d01fe',
      img: 'https://exxpozed-image.de/exxpozed-res.cloudinary.com/image/upload/q_auto:eco,w_1500,h_1500,c_pad,b_white,d_ph.gif,e_sharpen/v20230814123732/catalog/the-north-face-w-cragmont-fleece-jacket-21b-tnf-nf0a5a9l-gardenia-white-1.jpg',
      date_posted: new Date(Date.now()),
      description: '3fuck',
      top_id: 1,
      bottom_id: 3,
      outer_id: null,
      accessories_id: null,
      footwear_id: null,
    },
    {
      id: 4,
      user_id: 'auth0|65010b645218b17b091d01fe',
      img: 'https://exxpozed-image.de/exxpozed-res.cloudinary.com/image/upload/q_auto:eco,w_1500,h_1500,c_pad,b_white,d_ph.gif,e_sharpen/v20230814123732/catalog/the-north-face-w-cragmont-fleece-jacket-21b-tnf-nf0a5a9l-gardenia-white-1.jpg',
      date_posted: new Date(Date.now()),
      description: '4fuck',
      top_id: 1,
      bottom_id: 3,
      outer_id: null,
      accessories_id: null,
      footwear_id: null,
    },
    {
      id: 5,
      user_id: 'auth0|6500f4b1f6aa1817d80e5465',
      img: 'https://www.galaxiaradio.com/wp-content/uploads/2023/04/paloma-wool-jackets-womens-no-1009-hokusai-brown.jpg',
      date_posted: new Date(Date.now()),
      top_id: 2,
      description: '5fuck',
      bottom_id: 3,
      outer_id: 4,
      accessories_id: 7,
      footwear_id: 9,
    },
    {
      id: 6,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/2B823346-7DBB-40C2-8A4D-EFE0140DD299-47961-0000114CE4B02B73.jpg',
      date_posted: new Date(Date.now()),
      top_id: 53,
      description: 'Sporty and casual look! Good for summer!',
      bottom_id: null,
      outer_id: null,
      accessories_id: 42,
      footwear_id: 63,
    },
    {
      id: 7,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/3374E92D-9F69-47D0-AB4C-2FA5C4DAD432.JPG',
      date_posted: new Date(Date.now()),
      top_id: null,
      description: 'Mix and Match Outfits!',
      bottom_id: null,
      outer_id: 56,
      accessories_id: 68,
      footwear_id: 46,
    },
    {
      id: 8,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/AE8F8B8E-5502-4257-8CAC-4B5652AC17CC.jpg',
      date_posted: new Date(Date.now()),
      top_id: null,
      description: 'Casual look with my favourite items!',
      bottom_id: null,
      outer_id: null,
      accessories_id: 42,
      footwear_id: 46,
    },
    {
      id: 9,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/F4F65DBF-5158-47D6-ABD8-96A1133278F4-3126-000000A2C8EE5DDC.JPG',
      date_posted: new Date(Date.now()),
      top_id: null,
      description: 'Casual look with my favourite items!',
      bottom_id: null,
      outer_id: null,
      accessories_id: 62,
      footwear_id: null,
    },
    {
      id: 10,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/IMG_0343.jpeg',
      date_posted: new Date(Date.now()),
      top_id: 44,
      description: 'Comfy and casul look and having daldang',
      bottom_id: null,
      outer_id: null,
      accessories_id: 42,
      footwear_id: null,
    },
    {
      id: 11,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/IMG_2298.jpeg',
      date_posted: new Date(Date.now()),
      top_id: 53,
      description: 'Mix and match with sporty top and black blazer',
      bottom_id: null,
      outer_id: 56,
      accessories_id: null,
      footwear_id: 46,
    },
    {
      id: 12,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/IMG_2375.jpeg',
      date_posted: new Date(Date.now()),
      top_id: 45,
      description: 'Comfy but trying to fit in the occasion',
      bottom_id: 43,
      outer_id: 56,
      accessories_id: 51,
      footwear_id: 46,
    },
    {
      id: 13,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/IMG_2731.jpeg',
      date_posted: new Date(Date.now()),
      top_id: 45,
      description: 'Black and white look with bit of fun colour!',
      bottom_id: 57,
      outer_id: null,
      accessories_id: 51,
      footwear_id: 63,
    },
    {
      id: 14,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/IMG_2731.jpeg',
      date_posted: new Date(Date.now()),
      top_id: 45,
      description: 'Puffer all winter! Stay warm xx',
      bottom_id: 57,
      outer_id: 73,
      accessories_id: null,
      footwear_id: null,
    },
    {
      id: 15,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/IMG_3279.jpeg',
      date_posted: new Date(Date.now()),
      top_id: 75,
      description: 'Mooooo',
      bottom_id: null,
      outer_id: null,
      accessories_id: null,
      footwear_id: 61,
    },
    {
      id: 16,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/IMG_3830.jpeg',
      date_posted: new Date(Date.now()),
      top_id: 53,
      description: 'Good outfit for big temp gap',
      bottom_id: null,
      outer_id: 74,
      accessories_id: 68,
      footwear_id: 63,
    },
    {
      id: 17,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/IMG_5154.jpeg',
      date_posted: new Date(Date.now()),
      top_id: 75,
      description: 'Love knit and jeans combi',
      bottom_id: 76,
      outer_id: null,
      accessories_id: 60,
      footwear_id: 46,
    },
    {
      id: 18,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/IMG_5435.jpeg',
      date_posted: new Date(Date.now()),
      top_id: 44,
      description: 'Everyday outfit so in love with this!',
      bottom_id: 48,
      outer_id: 49,
      accessories_id: 68,
      footwear_id: 59,
    },
    {
      id: 19,
      user_id: 'auth0|6508ddcd7e52c58fd7f13549',
      img: '/images/outfits/IMG_5457.jpeg',
      date_posted: new Date(Date.now()),
      top_id: 69,
      description: 'Casual and sporty with some layers',
      bottom_id: null,
      outer_id: 50,
      accessories_id: null,
      footwear_id: 63,
    },
  ])
}
